name:   PI
channels:
  - conda-forge
  - nvidia
  - pytorch
  - pip
dependencies:
  - cudatoolkit=11.8
  - python=3.10
  - pytorch::pytorch=2.0.0
  - torchvision=0.15.0
  - pytesseract=0.3.10
  - pip:
      - opencv-python==4.6.0.66
      - mat73==0.59
      - imutils==0.5.4
      - grad-cam==1.4.6
      - pycocotools==2.0.6